### ISSUE TITLE
Typo in script

### ISSUE THREAD

**Issue by MauJFernandez** [itsKindred/jalesc#1]
Hi, you have a typo in line 240, it says `cat /etc/sudoeors` instead of `cat /etc/sudoers`.

https://github.com/itsKindred/jalesc/blob/7819d0af7ff89e0f910165079d024a68af7771b1/jalesc.sh#L240

**Comment by MauJFernandez** [comment]
Here's the PR #2.

**Comment by itsKindred** [comment]
PR Merged. Nice catch!
